language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- npm install -g grunt-cli
script:
- grunt test
before_deploy:
- grunt replace:version --tag=$TRAVIS_TAG --build=$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: viatsyshyn@gmail.com
  api_key:
    secure: EGUfzWJB3mLZ6joMRYEoDG/I3E7e/hCekaflhrL1DrMZvpefAboP/r88g3wa7TnpN3t7zsRXw+Nn4RScLf3O5ICNO5LncvcpQ4qIXa9y6oQ2cA4oUyDL46NQKnJclkTr5W4Qta0aRP8WO14XebYheIUQSOACqyNlJ6l6hRfk+AH7CjXE6ivJOFwHs2RZa57XTh+I0wJB4QBaYTg0tplZGVeDdy1DM/g22MdalDqyFDE9XHi2WnYSknnXE0EzKgGzsKcxo8OMtH8/YNyA2wjNkDZhvaZLueLMgO2ikhXCyUpbMMuk7LSdQ381t/IsQ4tWZa2ndkbgt6vq97dtGEn3nHOgTj0i1A5y7Jz25tWZvuvd+w6D/W8LoUsf8JsXdPgepyHyFTtaO80L0wilm75lvdgn1XaObnkn/BwH9bAIPH84pRoqI0WfUw5B3FP8bI4QRey66zqEpVmZRqe5OW0sDivvsvbQiiXLkHM/i72ksLqORGHNMO2tEyiobf2vvzqnMyYwY4qtjby0votJk+TGqMWi+97otzHdB7K0XPtvCP2kpa/QmVQybFJgTkK/xD0dempEQVA/BiqwCKy/z0/B5xFQ/Sai9Urpjfu5iHQ8XRP96WVFQlePEgYErJf8F9UnV1nocIFaA6SdpvEreT+Qjr63LnvNqXOzdeDpTGhDNP0=
  on:
    tags: true
    repo: viatsyshyn/grunt-jsbuild3
