language: node_js
node_js:
- '0.12'
sudo: false
before_install:
- npm install -g npm@next
before_script:
- npm install -g grunt-cli
script:
- grunt test
before_deploy:
- grunt replace:version --tag=$TRAVIS_TAG --build=$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: viatsyshyn@gmail.com
  api_key:
    secure: Kgh+R/bOUX1gXkPJY886CZds0oXEPCS6fMi2R39Lrr24gg/39eYgq01FkfBZXt0L/Fib/Q7S6VET0Jz6Jp5l6jwH6vE7W1MetMVwXbG6w7J2OPvdiwkg392b+ZfYgv2nDmoOcaVLXx66U9aTBYtg5nJi96pXCDqzJzI3gwguBC3wB88HpVL3J9eGe6mr57sxEcVgNnXpwMG/qchoTJcOEkoSLDqk+cuG9Nb/wZ3EF6GW4u3M6JgjRKTsCS/xuIQY5NODOz03Fj9W8cVPuY8OEEDrgQOqF6d1NBlZ7qwnuLWFIEKtisv3BxHv777PgkRDmVpEBJ0n7NcLwm6gSg2bRL9FFF2idZtUT/HPQEYQv45V04TCButK2CT1n73td7yOx+m6VWhtJ93o8wIlnuOxCp7kb/LVZngDqN9okcq3vrMISvtqEr6mxcrFCIMLg8cMN0OtKNnnglUnH0UdyTX3NRWJ3bDdX3NvYi7ON0xFBjbYRCESYL9vhtQPC2e+dE2m9bHKQOecCebhwfwbUbUu2iBbFTGrdB6/3sgTVe5ZM/wW7fbZJBkmnT2UbgYHZYDVzmCVnUlaMVhSIH2yj2XAIFnSKSl3yO4PTL/o+ryKIEf4UjYRRva9jCyDENdtIWfps47hDHQ6QJ6tIMuSqUIiiuUUrYikMRS9JQoy3DEW3S0=
  on:
    tags: true
    repo: viatsyshyn/grunt-jsbuild3
