language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- npm install -g grunt-cli
script:
- grunt test
before_deploy:
- grunt replace:version --tag=$TRAVIS_TAG --build=$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: viatsyshyn@gmail.com
  api_key:
    secure: Bdz4Tb4Tg+hX8XFdE1jkDbW84q32Rf9/Y7i/PdjSj66lr+GOfyooSMCENLUbc6R2G045Y+KdzRjsIuOU5f68Kf4QVFg3dBxOOcW4+kD/gQ0si5baoVtt5ImF12XXxVY0ZQORplQU2XtDuQ2PHk1UxT7LeOePyXw/SBL2XyOJPEl50IPN5G8L4dfO2AicpuwKXWNFA7vPNo22S8f33cLKvGR2KAUr1Jsbvm8N/ExysWVmFyVouQjjdHUHkJin7XQAkqAlCYwYaGQF4/1rAqvdLZhT+/HKo/0nN6DCYFdlASoeA4idUZS/sS3BzuplURYRVNvzfu8FkhXPbjTXNW0kLYo+0toJ+FMb402gncp5I6jUrlVTQCrNUvtbh/EEzAaJA3w0ZuOeQJzrMegBvgKOF3oZPHVEtUbMGlJmdr9y/gJiyEqh6GUZjR+PuVuNCG3ygKV8f80Ei3d7+KoQ6TVuPK04jGlT9XaQEpMqhXpmx4lZ4B+gYq1tW8dJkr3fZwNn5bsk3xSI+6JXnqt25xCUHl9X4aopMwTIPjK1fMIS0DtYowbMMSRccan7/a33Iw7dsdqH6gU4MfxmXzkTmv0/kguJxgXKgXBV9qlirHYJL85txeS+foXfMTaC74NCGgvZf6ZGk4SHDHVZbrkp014fohyAkZXqfLgKBGstRPaSv3M=
  skip_cleanup: true
  on:
    tags: true
    repo: viatsyshyn/grunt-jsbuild3
